gulp = require 'gulp'
nodemon = require 'gulp-nodemon'
watch = require 'gulp-watch'
concat = require 'gulp-concat'
coffee = require 'gulp-coffee'
cjsx = require 'gulp-cjsx'
browserify = require 'browserify'
transform = require 'vinyl-transform'
uglify = require 'gulp-uglify'
sass = require 'gulp-sass'
uncss = require 'gulp-uncss'
csso = require 'gulp-csso'
wait = require 'gulp-wait'

gulp.task 'cjsx', ->
  gulp.src './assets/*.cjsx'
      .pipe cjsx(bare: true)
      .pipe gulp.dest './src/js/'

gulp.task 'cjsx_global', ->
  gulp.src './assets/global*.cjsx'
      .pipe cjsx(bare: true)
      .pipe gulp.dest './src/js/global/'

gulp.task 'browserify', ['cjsx'], ->
  browserified = transform (filename)->
    b = browserify(filename)
    b.bundle()

  gulp.src './src/js/*.js'
      # .pipe concat 'header.js'
      .pipe browserified
      # .pipe uglify()
      .pipe gulp.dest './public/js/'

gulp.task 'browserify_global', ['cjsx_global'], ->
  browserified = transform (filename)->
    b = browserify(filename)
    b.bundle()

  gulp.src './src/js/global/*.js'
      .pipe concat 'header.js'
      .pipe browserified
      # .pipe uglify()
      .pipe gulp.dest './public/js/'

gulp.task 'sass', ['start_server'],->
  gulp.src './src/scss/*.scss'
      .pipe(sass())
      .pipe(concat('styles.css'))
      # .pipe wait(5000)
      # .pipe(uncss({
      #     html: [
      #       'http://localhost:3000/welcome'
      #       'http://localhost:3000/login'
      #       'http://localhost:3000/me/dashboard'
      #       'http://getbootstrap.com/examples/theme/'
      #     ]
      #     ignore: [
      #       '.open > .dropdown-menu'
      #       '/.*/'
      #     ]
      # }))
      # .pipe csso()
      .pipe gulp.dest('./public/css')

gulp.task 'start_server', ->
  nodemon(
    script: 'app.coffee'
    ext: 'coffee'
    env:  ('NODE_ENV': 'development', 'port': 3000)
    # ignore: ['gulpfile.coffee']
  ).on 'restart', ->
    console.log 'restarted!'

# ---
# generated by js2coffee 2.0.0

gulp.task 'watch', ->
  gulp.watch './assets/*.cjsx', ['browserify']
  gulp.watch './assets/global/*.cjsx', ['browserify_global']
  gulp.watch './src/scss/*.s*ss', ['sass']

gulp.task('default', ['browserify_global', 'browserify', 'sass', 'watch']) ;
